dsr_position_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
       - joint1
       - joint2
       - joint3
       - joint4
       - joint5
       - joint6
    write_op_modes:
       - joint1
       - joint2
       - joint3
       - joint4
       - joint5
       - joint6
    state_publish_rate: 25
    action_monitor_rate: 20
    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 5

dsr_joint_publisher:
  ros__parameters:
    type: joint_state_controller/JointStateController
    publish_rate: 100