default_planning_pipeline: ompl
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
moveit_manage_controllers: true

planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/joint_states"
  attached_collision_object_topic: "/moveit_cpp/planning_scene_monitor"
  publish_planning_scene_topic: "/moveit_cpp/publish_planning_scene"
  monitored_planning_scene_topic: "/moveit_cpp/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_pipelines:
  pipeline_names: ["ompl", "pilz_industrial_motion_planner"]

plan_request_params:
  planning_attempts: 1
  planning_pipeline: ompl
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0

ompl_rrtc: # Namespace for individual plan request
  plan_request_params: # PlanRequestParameters similar to the ones that are used by the single pipeline planning of moveit_cpp
    planning_attempts: 1 # Number of attempts the planning pipeline tries to solve a given motion planning problem
    planning_pipeline: ompl # Name of the pipeline that is being used
    planner_id: "RRTConnectkConfigDefault" # Name of the specific planner to be used by the pipeline
    max_velocity_scaling_factor: 1.0 # Velocity scaling parameter for the trajectory generation algorithm that is called (if configured) after the path planning
    max_acceleration_scaling_factor: 1.0 # Acceleration scaling parameter for the trajectory generation algorithm that is called (if configured) after the path planning
    planning_time: 1.0 # Time budget for the motion plan request. If the planning problem cannot be solved within this time, an empty solution with error code is returned

pilz_lin:
  plan_request_params:
    planning_attempts: 1
    planning_pipeline: pilz_industrial_motion_planner
    planner_id: "PTP"
    max_velocity_scaling_factor: 1.0
    max_acceleration_scaling_factor: 1.0
    planning_time: 0.8

ompl:
  arm:
    planner_configs:
      - APSConfigDefault
      - SBLkConfigDefault
      - ESTkConfigDefault
      - LBKPIECEkConfigDefault
      - BKPIECEkConfigDefault
      - KPIECEkConfigDefault
      - RRTkConfigDefault
      - RRTConnectkConfigDefault
      - RRTstarkConfigDefault
      - TRRTkConfigDefault
      - PRMkConfigDefault
      - PRMstarkConfigDefault
      - FMTkConfigDefault
      - BFMTkConfigDefault
      - PDSTkConfigDefault
      - STRIDEkConfigDefault
      - BiTRRTkConfigDefault
      - LBTRRTkConfigDefault
      - BiESTkConfigDefault
      - ProjESTkConfigDefault
      - LazyPRMkConfigDefault
      - LazyPRMstarkConfigDefault
      - SPARSkConfigDefault
      - SPARStwokConfigDefault
      - TrajOptDefault
  planner_configs:
    APSConfigDefault:
      hybridize: 1
      max_hybrid_paths: 36
      num_planners: 8
      planners: RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect,RRTConnect
      shortcut: 1
      type: geometric::AnytimePathShortening
    BFMTkConfigDefault:
      balanced: 0
      cache_cc: 1
      extended_fmt: 1
      heuristics: 1
      nearest_k: 1
      num_samples: 1000
      optimality: 1
      radius_multiplier: 1.0
      type: geometric::BFMT
    BKPIECEkConfigDefault:
      border_fraction: 0.9
      failed_expansion_score_factor: 0.5
      min_valid_path_fraction: 0.5
      range: 0.0
      type: geometric::BKPIECE
    BiESTkConfigDefault:
      range: 0.0
      type: geometric::BiEST
    BiTRRTkConfigDefault:
      cost_threshold: 1e300
      frountier_node_ratio: 0.1
      frountier_threshold: 0.0
      init_temperature: 100
      range: 0.0
      temp_change_factor: 0.1
      type: geometric::BiTRRT
    ESTkConfigDefault:
      goal_bias: 0.05
      range: 0.0
      type: geometric::EST
    FMTkConfigDefault:
      cache_cc: 1
      extended_fmt: 1
      heuristics: 0
      nearest_k: 1
      num_samples: 1000
      radius_multiplier: 1.1
      type: geometric::FMT
    KPIECEkConfigDefault:
      border_fraction: 0.9
      failed_expansion_score_factor: 0.5
      goal_bias: 0.05
      min_valid_path_fraction: 0.5
      range: 0.0
      type: geometric::KPIECE
    LBKPIECEkConfigDefault:
      border_fraction: 0.9
      min_valid_path_fraction: 0.5
      range: 0.0
      type: geometric::LBKPIECE
    LBTRRTkConfigDefault:
      epsilon: 0.4
      goal_bias: 0.05
      range: 0.0
      type: geometric::LBTRRT
    LazyPRMkConfigDefault:
      range: 0.0
      type: geometric::LazyPRM
    LazyPRMstarkConfigDefault:
      type: geometric::LazyPRMstar
    PDSTkConfigDefault:
      type: geometric::PDST
    PRMkConfigDefault:
      max_nearest_neighbors: 10
      type: geometric::PRM
    PRMstarkConfigDefault:
      type: geometric::PRMstar
    ProjESTkConfigDefault:
      goal_bias: 0.05
      range: 0.0
      type: geometric::ProjEST
    RRTConnectkConfigDefault:
      range: 0.0
      type: geometric::RRTConnect
    RRTkConfigDefault:
      goal_bias: 0.05
      range: 0.0
      type: geometric::RRT
    RRTstarkConfigDefault:
      delay_collision_checking: 1
      goal_bias: 0.05
      range: 0.0
      type: geometric::RRTstar
    SBLkConfigDefault:
      range: 0.0
      type: geometric::SBL
    SPARSkConfigDefault:
      dense_delta_fraction: 0.001
      max_failures: 1000
      sparse_delta_fraction: 0.25
      stretch_factor: 3.0
      type: geometric::SPARS
    SPARStwokConfigDefault:
      dense_delta_fraction: 0.001
      max_failures: 5000
      sparse_delta_fraction: 0.25
      stretch_factor: 3.0
      type: geometric::SPARStwo
    STRIDEkConfigDefault:
      degree: 16
      estimated_dimension: 0.0
      goal_bias: 0.05
      max_degree: 18
      max_pts_per_leaf: 6
      min_degree: 12
      min_valid_path_fraction: 0.2
      range: 0.0
      type: geometric::STRIDE
      use_projected_distance: 0
    TRRTkConfigDefault:
      frountierNodeRatio: 0.1
      frountier_threshold: 0.0
      goal_bias: 0.05
      init_temperature: 10e-6
      k_constant: 0.0
      max_states_failed: 10
      min_temperature: 10e-10
      range: 0.0
      temp_change_factor: 2.0
      type: geometric::TRRT
    TrajOptDefault:
      type: geometric::TrajOpt
  planning_plugin: ompl_interface/OMPLPlanner
  request_adapters:
    default_planner_request_adapters/AddTimeOptimalParameterization
    default_planner_request_adapters/ResolveConstraintFrames default_planner_request_adapters/FixWorkspaceBounds
    default_planner_request_adapters/FixStartStateBounds default_planner_request_adapters/FixStartStateCollision
    default_planner_request_adapters/FixStartStatePathConstraints
  start_state_max_bounds_error: 0.1
pilz_industrial_motion_planner:
  capabilities: pilz_industrial_motion_planner/MoveGroupSequenceAction pilz_industrial_motion_planner/MoveGroupSequenceService
  default_planner_config: LIN
  planning_plugin: pilz_industrial_motion_planner/CommandPlanner
  request_adapters:
    default_planner_request_adapters/FixWorkspaceBounds default_planner_request_adapters/FixStartStateBounds
    default_planner_request_adapters/FixStartStateCollision default_planner_request_adapters/FixStartStatePathConstraints
